spring.application.name=futdb
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5433/futdb
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

futdatabase.base-url=https://api.futdatabase.com/api
futdatabase.api-key=${FUTDATABASE_API_KEY}

thesportsdb.api-key=123