-- Schema do banco futdb (PostgreSQL).
-- O backend roda com spring.jpa.hibernate.ddl-auto=validate, então as tabelas
-- precisam existir antes de subir a aplicação. Espelha as entidades em
-- src/main/java/br/com/futnerds/futdb/model.

CREATE EXTENSION IF NOT EXISTS unaccent;

CREATE TABLE IF NOT EXISTS nacao (
    id            bigint PRIMARY KEY,
    nome          varchar,
    bandeira_url  varchar
);

CREATE TABLE IF NOT EXISTS liga (
    id          bigint PRIMARY KEY,
    nome        varchar,
    nacao_id    bigint REFERENCES nacao (id),
    imagem_url  varchar
);

CREATE TABLE IF NOT EXISTS clube (
    id                  bigint PRIMARY KEY,
    nome                varchar,
    liga_id             bigint REFERENCES liga (id),
    clube_pai_id        bigint,
    escudo_url          varchar,
    estadio             varchar,
    cidade              varchar,
    capacidade_estadio  integer,
    fundacao            integer,
    id_the_sports_db    varchar
);

CREATE TABLE IF NOT EXISTS jogador (
    id                      bigint PRIMARY KEY,
    nome                    varchar,
    nome_comum              varchar,
    idade                   smallint,
    altura                  smallint,
    peso                    smallint,
    pe_dominante            varchar,
    posicao                 varchar,
    posicoes_alternativas   varchar,
    overall                 smallint,
    potencial               smallint,
    raridade_id             bigint,
    nacao_id                bigint REFERENCES nacao (id),
    clube_id                bigint REFERENCES clube (id),
    liga_id                 bigint REFERENCES liga (id),
    foto_url                varchar,
    preco_pc                bigint,
    preco_console           bigint,
    salario                 bigint,
    velocidade              smallint,
    finalizacao             smallint,
    passe                   smallint,
    drible                  smallint,
    traits                  varchar,
    cruzamento              smallint,
    finalizacao_detalhada   smallint,
    cabeceio                smallint,
    passe_curto             smallint,
    voleio                  smallint,
    drible_detalhado        smallint,
    curva                   smallint,
    precisao_falta          smallint,
    passe_longo             smallint,
    controle_de_bola        smallint,
    aceleracao              smallint,
    velocidade_sprint       smallint,
    agilidade               smallint,
    reacoes                 smallint,
    equilibrio              smallint,
    potencia_chute          smallint,
    impulsao                smallint,
    folego                  smallint,
    forca                   smallint,
    chutes_de_longe         smallint,
    agressao                smallint,
    interceptacao           smallint,
    posicionamento          smallint,
    visao                   smallint,
    penaltis                smallint,
    compostura              smallint,
    marcacao                smallint,
    desarme_em_pe           smallint,
    desarme_deslizante      smallint,
    goleiro_elasticidade    smallint,
    goleiro_agarrar         smallint,
    goleiro_chute           smallint,
    goleiro_posicionamento  smallint,
    goleiro_reflexos        smallint,
    atualizado_em           timestamp(6)
);

CREATE INDEX IF NOT EXISTS idx_jogador_clube ON jogador (clube_id);
CREATE INDEX IF NOT EXISTS idx_jogador_liga ON jogador (liga_id);
CREATE INDEX IF NOT EXISTS idx_jogador_nacao ON jogador (nacao_id);
CREATE INDEX IF NOT EXISTS idx_clube_liga ON clube (liga_id);

-- Sem FK para jogador: o histórico inclui jogadores que não estão na edição atual.
CREATE TABLE IF NOT EXISTS jogador_historico (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jogador_id  bigint,
    edicao      smallint,
    overall     smallint,
    potencial   smallint,
    clube       varchar,
    liga        varchar,
    CONSTRAINT uk_jogador_historico_jogador_edicao UNIQUE (jogador_id, edicao)
);

CREATE TABLE IF NOT EXISTS uniforme (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clube_id    bigint REFERENCES clube (id),
    tipo        varchar,
    imagem_url  varchar,
    temporada   varchar
);

CREATE INDEX IF NOT EXISTS idx_uniforme_clube ON uniforme (clube_id);
